/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover the public API */
        get: operations["api_index_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect the effective price table */
        get: operations["get_pricing_api_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Events */
        get: operations["session_events_api_sessions_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarize a session by agent */
        get: operations["get_agent_summary_api_sessions__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect session parse diagnostics */
        get: operations["get_diagnostics_api_sessions__session_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a session's findings by estimated cost and severity */
        get: operations["get_findings_api_sessions__session_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_api_sessions__session_id__nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSummaryOut */
        AgentSummaryOut: {
            /** Schema Version */
            schema_version: number;
            /** Id */
            id: string;
            /** Mtime */
            mtime: number;
            /** Agents */
            agents: components["schemas"]["AgentSummaryRowOut"][];
        };
        /** AgentSummaryRowOut */
        AgentSummaryRowOut: {
            /** Agent Id */
            agent_id: number;
            /** Harness Agent Id */
            harness_agent_id: string | null;
            /** Parent Agent Id */
            parent_agent_id: number | null;
            /** Topic */
            topic: string;
            /** Models */
            models: string[];
            llm_calls: components["schemas"]["MetricOut"];
            context_peak: components["schemas"]["MetricOut"];
            tokens: components["schemas"]["TokensOut"];
            own_cost: components["schemas"]["CostOut"];
            subtree_cost: components["schemas"]["CostOut"];
            start: components["schemas"]["MetricOut"];
            end: components["schemas"]["MetricOut"];
            /** Cost Parts */
            cost_parts: {
                [key: string]: components["schemas"]["CostOut"];
            };
            /** Cache Ttl */
            cache_ttl: string;
            cold_rewrites: components["schemas"]["MetricOut"];
            cold_rewrite_cost: components["schemas"]["CostOut"];
            longest_gap: components["schemas"]["MetricOut"];
            /** Findings Count */
            findings_count: number;
            /** Resume Count */
            resume_count: number;
        };
        /** ApiEndpointOut */
        ApiEndpointOut: {
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Parameters */
            parameters: string[];
            /** Description */
            description: string;
        };
        /** ApiIndexOut */
        ApiIndexOut: {
            /** Endpoints */
            endpoints: components["schemas"]["ApiEndpointOut"][];
        };
        /** CallEventOut */
        CallEventOut: {
            /** Kind */
            kind: string;
            /** Event Id */
            event_id: string;
            start: components["schemas"]["MetricOut"];
            end: components["schemas"]["MetricOut"];
            duration: components["schemas"]["MetricOut"];
        };
        /** CostOut */
        CostOut: {
            /** Value */
            value: number | null;
            /** Unit */
            unit: string | null;
            /** Usd */
            usd: number | null;
            /** Provenance */
            provenance: string;
        };
        /** DiagnosticsDetailOut */
        DiagnosticsDetailOut: {
            /** Malformed Lines */
            malformed_lines: number;
            /** Unknown Tool Ids */
            unknown_tool_ids: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
            /** Malformed Line Details */
            malformed_line_details: components["schemas"]["MalformedLineDetailOut"][];
        };
        /** DiagnosticsOut */
        DiagnosticsOut: {
            /** Malformed Lines */
            malformed_lines: number;
            /** Unknown Tool Ids */
            unknown_tool_ids: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
        };
        /** EventCallLinkOut */
        EventCallLinkOut: {
            /** Source Request Id */
            source_request_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "requested_by" | "consumed_by" | "next_observed_call";
            /**
             * Evidence
             * @enum {string}
             */
            evidence: "recorded" | "observed_order";
            /** Owner Id */
            owner_id?: string | null;
        };
        /** ExecutionEventOut */
        ExecutionEventOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "user_input" | "tool_start" | "tool_result" | "delegation" | "child_completion" | "completion" | "message" | "resume" | "compaction";
            /** Event Id */
            event_id?: string | null;
            /** Subject Node Id */
            subject_node_id?: string | null;
            start: components["schemas"]["MetricOut"];
            /** Source Order */
            source_order?: number | null;
            /** Source Stream Id */
            source_stream_id?: string | null;
            /** Success */
            success?: boolean | null;
            /** Links */
            links: components["schemas"]["EventCallLinkOut"][];
            execution_start: components["schemas"]["MetricOut"];
            execution_end: components["schemas"]["MetricOut"];
        };
        /** FindingOut */
        FindingOut: {
            /** Heuristic Id */
            heuristic_id: string;
            /** Node Id */
            node_id: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            estimated_avoidable_cost: components["schemas"]["CostOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LlmCallOut */
        LlmCallOut: {
            /** Call Id */
            call_id: string | null;
            start: components["schemas"]["MetricOut"];
            duration: components["schemas"]["MetricOut"];
            /** Model */
            model: string | null;
            tokens: components["schemas"]["TokensOut"];
            cost: components["schemas"]["CostOut"];
            /** In Context */
            in_context: boolean;
            /** Cost Parts */
            cost_parts: {
                [key: string]: components["schemas"]["CostOut"];
            };
            /** Price Prefix */
            price_prefix: string | null;
            gap: components["schemas"]["MetricOut"];
            /** Gap Basis */
            gap_basis: string | null;
            /** Preceding Events */
            preceding_events: components["schemas"]["CallEventOut"][];
            /** Cold Reason */
            cold_reason: string;
            /** Cold Rewrite */
            cold_rewrite: boolean;
            /** Source Request Id */
            source_request_id?: string | null;
            /** Source Order */
            source_order?: number | null;
            /** Source Stream Id */
            source_stream_id?: string | null;
            /**
             * Timing Basis
             * @default unknown
             * @enum {string}
             */
            timing_basis: "request_start" | "assistant_message" | "usage_report" | "turn_start" | "unknown";
        };
        /** MalformedLineDetailOut */
        MalformedLineDetailOut: {
            /** Source Path */
            source_path: string;
            /** Line Number */
            line_number: number;
            /** Excerpt */
            excerpt: string;
            /** Error Category */
            error_category: string;
        };
        /** MetricOut */
        MetricOut: {
            /** Value */
            value: number | null;
            /** Provenance */
            provenance: string;
        };
        /**
         * ModelPriceOut
         * @description USD rate per million tokens for each token kind.
         */
        ModelPriceOut: {
            /** Input */
            input: number;
            /** Output */
            output: number;
            /** Cache Read */
            cache_read: number;
            /** Cache Write 5M */
            cache_write_5m: number;
            /** Cache Write 1H */
            cache_write_1h: number;
        };
        /** NodeDetailOut */
        NodeDetailOut: {
            /** Node Id */
            node_id: string;
            /** Prompt */
            prompt: string;
            /** Result */
            result: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
        };
        /** NodeOut */
        NodeOut: {
            /** Node Id */
            node_id: string;
            /** Agent Id */
            agent_id: number | null;
            /** Harness Agent Id */
            harness_agent_id: string | null;
            /** Active */
            active: boolean;
            /** Active Descendant */
            active_descendant: boolean;
            /** Activity */
            activity: string | null;
            /** Kind */
            kind: string;
            /** Topic */
            topic: string;
            /** Model */
            model: string | null;
            /** Success */
            success: boolean | null;
            tool: components["schemas"]["ToolOut"] | null;
            start: components["schemas"]["MetricOut"];
            end: components["schemas"]["MetricOut"];
            duration: components["schemas"]["MetricOut"];
            user_wait: components["schemas"]["MetricOut"];
            llm_call_count: components["schemas"]["MetricOut"];
            tool_call_count: components["schemas"]["MetricOut"];
            tokens: components["schemas"]["TokensOut"];
            tokens_total: components["schemas"]["TokensOut"];
            cost_total: components["schemas"]["CostOut"];
            cost_own: components["schemas"]["CostOut"];
            context_peak: components["schemas"]["MetricOut"];
            /** Compactions */
            compactions: components["schemas"]["MetricOut"][];
            /** Resume Times */
            resume_times: components["schemas"]["MetricOut"][];
            /** Llm Calls */
            llm_calls: components["schemas"]["LlmCallOut"][];
            /** Execution Events */
            execution_events?: components["schemas"]["ExecutionEventOut"][];
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Children */
            children: components["schemas"]["NodeOut"][];
        };
        /**
         * PricingOut
         * @description The configured price table and its model matching rule.
         */
        PricingOut: {
            /** Source */
            source: string | null;
            /** Date */
            date: string | null;
            /** Unit */
            unit: string;
            /** Usd Per Credit */
            usd_per_credit: number;
            /** Matching Rule */
            matching_rule: string;
            /** Models */
            models: {
                [key: string]: components["schemas"]["ModelPriceOut"];
            };
        };
        /**
         * ProjectedNodeOut
         * @description A tree node in a bounded response; children may be omitted by depth.
         */
        ProjectedNodeOut: {
            /** Node Id */
            node_id: string;
            /** Agent Id */
            agent_id: number | null;
            /** Harness Agent Id */
            harness_agent_id: string | null;
            /** Active */
            active: boolean;
            /** Active Descendant */
            active_descendant: boolean;
            /** Activity */
            activity: string | null;
            /** Kind */
            kind: string;
            /** Topic */
            topic: string;
            /** Model */
            model: string | null;
            /** Success */
            success: boolean | null;
            tool: components["schemas"]["ToolOut"] | null;
            start: components["schemas"]["MetricOut"];
            end: components["schemas"]["MetricOut"];
            duration: components["schemas"]["MetricOut"];
            user_wait: components["schemas"]["MetricOut"];
            llm_call_count: components["schemas"]["MetricOut"];
            tool_call_count: components["schemas"]["MetricOut"];
            tokens: components["schemas"]["TokensOut"];
            tokens_total: components["schemas"]["TokensOut"];
            cost_total: components["schemas"]["CostOut"];
            cost_own: components["schemas"]["CostOut"];
            context_peak: components["schemas"]["MetricOut"];
            /** Compactions */
            compactions: components["schemas"]["MetricOut"][];
            /** Resume Times */
            resume_times: components["schemas"]["MetricOut"][];
            /** Llm Calls */
            llm_calls: components["schemas"]["LlmCallOut"][];
            /** Execution Events */
            execution_events?: components["schemas"]["ExecutionEventOut"][];
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Children */
            children: components["schemas"]["ProjectedNodeOut"][];
            /** Children Omitted */
            children_omitted?: boolean | null;
        };
        /**
         * ProjectedSessionOut
         * @description Optional top-level groups selected with the `fields` query parameter.
         */
        ProjectedSessionOut: {
            /** Id */
            id?: string | null;
            /** Agent */
            agent?: string | null;
            /** Title */
            title?: string | null;
            /** Workspace */
            workspace?: string | null;
            /** Mtime */
            mtime?: number | null;
            /** Sources */
            sources?: string[] | null;
            diagnostics?: components["schemas"]["DiagnosticsOut"] | null;
            root?: components["schemas"]["ProjectedNodeOut"] | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Title */
            title: string;
            /** Workspace */
            workspace: string | null;
            /** Mtime */
            mtime: number;
            /** Sources */
            sources: string[];
            diagnostics: components["schemas"]["DiagnosticsOut"];
            root: components["schemas"]["NodeOut"];
        };
        /** SummaryOut */
        SummaryOut: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Title */
            title: string;
            /** Workspace */
            workspace: string | null;
            /** State */
            state: string;
            /** Mtime */
            mtime: number;
            /** Start Ms */
            start_ms: number | null;
            /** Last Activity Ms */
            last_activity_ms: number | null;
            /** End Ms */
            end_ms: number | null;
            /** File Size */
            file_size: number | null;
            cost_total: components["schemas"]["CostOut"] | null;
            /** Error */
            error: string | null;
        };
        /** TokensOut */
        TokensOut: {
            input: components["schemas"]["MetricOut"];
            output: components["schemas"]["MetricOut"];
            cache_read: components["schemas"]["MetricOut"];
            cache_write: components["schemas"]["MetricOut"];
            cache_write_5m: components["schemas"]["MetricOut"];
            cache_write_1h: components["schemas"]["MetricOut"];
        };
        /** ToolOut */
        ToolOut: {
            /** Native Id */
            native_id: string;
            /** Category */
            category: string;
            /** Path */
            path: string | null;
            /** Paths */
            paths: string[];
            /** Line Range */
            line_range: [
                number,
                number
            ] | null;
            /** Command */
            command: string | null;
            /** Writes File */
            writes_file: boolean;
            /** Target Agent Id */
            target_agent_id: string | null;
            /** Is Resume */
            is_resume: boolean;
            /** Linked Agent Node Id */
            linked_agent_node_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_index_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiIndexOut"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"][];
                };
            };
        };
    };
    get_pricing_api_pricing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingOut"];
                };
            };
        };
    };
    session_events_api_sessions_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_agent_summary_api_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostics_api_sessions__session_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_findings_api_sessions__session_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: {
                /** @description Maximum depth from root (root is 0); truncated nodes report children_omitted. */
                depth?: number | null;
                /** @description Groups: session (identity and sources), diagnostics, tree (root); comma-separated. */
                fields?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"] | components["schemas"]["ProjectedSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_api_sessions__session_id__nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
